# Generated by Django 5.1.1 on 2024-09-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=1, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rules',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pricerange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodateApp.pricerange'),
        ),
    ]
