# Generated by Django 5.1.1 on 2024-09-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodateApp', '0004_rename_images_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='landmark',
            field=models.TextField(default=0, max_length=200, null=True),
        ),
    ]
