# Generated by Django 5.1.1 on 2024-09-25 14:05

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodateApp', '0005_product_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
