# Generated by Django 5.1.1 on 2024-10-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodateApp', '0008_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms',
        ),
        migrations.AddField(
            model_name='product',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='accommodateApp.amenities'),
        ),
        migrations.AddField(
            model_name='product',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='accommodateApp.rooms'),
        ),
    ]
