# Generated by Django 5.1.1 on 2024-10-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodateApp', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='products',
        ),
    ]
