# Generated by Django 5.1.1 on 2024-10-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodateApp', '0012_rename_product_comment_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(related_name='products', to='accommodateApp.comment'),
        ),
    ]
