# Generated by Django 5.1.1 on 2024-10-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodateApp', '0016_alter_manager_email_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='password',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='username',
        ),
    ]
